- source/_data/MCPubs.bib
- source/publications/index.md
This PR include: 1) Update index.md for ATC'20 2) Add Best paper badge for Leap 3) Add acceptance rate for all conferences.
> Fix ATC index & Add acceptance rate

- source/_data/MCPubs.bib
> Fix Salus slide link

- source/_custom/styles.styl
- use more compact line height for posts
- consistently use medium size font regardless of screen resolution
> Tweak font settings, fix #25

- source/people/index.md
> Add Sanjay's name

- README.md
- _config.yml
- source/publications/index.md
> Fix MLSys'21 acceptance rate

- source/_data/SymbioticLab.bib
- source/projects/index.md
So that we can put upcoming AI/ML papers under this category.
Also, added missing badges for NetLock. Should've created a separate pull request though :|
> Updates and missing info

- source/_data/SymbioticLab.bib
forgot to add the link in last commit :)
> add fedscale repo link

- source/_data/SymbioticLab.bib
- source/_posts/oort-wins-the-distinguished-artifact-award-at-osdi2021.md
> Oort wins the Distinguished Artifact Award at OSDI'2021! 

- source/_posts/peifeng-has-phinished.md
- source/people/index.md
> Peifeng has phinished

- source/people/index.md
Added LinkedIn links for @juncgu and @Aetf, as per the discussion during lunch today.
> Add LinkedIn links for people who graduated

- source/_data/SymbioticLab.bib
> Add dissertation of Jie You

- source/_data/SymbioticLab.bib
The corresponding issue will be left open since we later need to replace the entry with the NSDI CR version.
> Add Zeus arxiv paper in pubs

- source/people/index.md
Added Luoxi and unified list numbers to 1. It's going to rendered as 1, 2, 3, 4, just like the Current Ph.D. Students list.
> Add Luoxi to people

- source/_data/SymbioticLab.bib
Noticed Infiniswap has a homepage link in the publist.
> Add homepage links for FedScale and Zeus

- source/people/index.md
I replace my stale homepage url with the new one.
> Update homepage link

- source/_front.md
Can get the permission of editing this repo btw?
> Minor typo in _front.md

- custom/styles.styl
> Pack menu items together a bit

- source/_data/SymbioticLab.bib
FedScale deployment at LinkedIn
> FLINT arXiv

- source/_data/SymbioticLab.bib
> Fan Thesis

- source/_front.md
Real quick formatting nitpicking typical Jae-Won thing
> Consistent link formatting

- source/_data/SymbioticLab.bib
> add badges to Oobleck

- source/_front.md
- source/cluster/index.md
> Cluster linked.

- source/_data/SymbioticLab.bib
> Update auxo title

- source/_data/SymbioticLab.bib
Sorry about the inconvenience! @mosharaf
> Update Venn's author 

- source/_data/SymbioticLab.bib
> fix fedtrans paper

- source/people/index.md
Remaining alumni placement will be updated when they are finalized.
> Personnel updates

- .github/workflows/check.yml
- .github/workflows/ci-workflow.yml
- source/_data/SymbioticLab.bib
> curie arxiv

- source/_data/SymbioticLab.bib
> Add ML.ENERGY Benchmark paper
